### ISSUE TITLE
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by brice-noowu** [ngneat/aim#24]
When trying to generate a component, it gives : 
`An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID`

**Comment by brice-noowu** [comment]
Please @NetanelBasal could you fix this ? Or at least point me in the right direction, if I can help

**Comment by shaharkazaz** [comment]
@brice-noowu This is related to the angular schematics.
Can you please share the version of your installed `@schematics/angular` package?

**Comment by brice-noowu** [comment]
Upgrading `@schematics/angular` to `^13.2.0` fixed the problem ,thanks
