### ISSUE TITLE
aim-to-standalone does not support nrwl secondary endpoint?

### ISSUE THREAD

**Issue by wizardnet972** [ngneat/aim#30]
`aim-to-standalone` does not support converting aim components to standalone in [nrwl secondary endpoint](https://nx.dev/packages/angular/generators/library-secondary-entry-point)

https://github.com/wizardnet972/nx-standalone/blob/main/libs/ng-lib/baz/src/lib/foo/foo.component.ts

```
➜  nx-standalone git:(main) ✗ npx @ngneat/aim-to-standalone start
? Path to tsconfig file tsconfig.base.json
✔ Resolved dependencies and AIMs.
✔ Refactored to AIM.
✔ Saved.
```

Although there is a message that it succeeded, nothing has changed in this path: `libs/ng-lib/baz/src/lib/foo/foo.component.ts`

**Comment by NetanelBasal** [comment]
<img width="1539" alt="Screen Shot 2022-06-07 at 21 47 08" src="https://user-images.githubusercontent.com/6745730/172459083-75075c1e-8231-40ce-9ff4-3a8142eb3b81.png">

**Comment by wizardnet972** [comment]
@NetanelBasal 

I run it again and it works in my repo. 
So I debug the cli in my project and I found the problem.

My project has aim components and angular regular components without `ngModule` in the files.

So the cli is going though all the files and stops when it is not found `ngModule` in the file because in the code contain `return`. this should change to `continue` to move to the next file: 

https://github.com/ngneat/aim/blob/master/aim-to-standalone/src/to-standalone.ts#L131
```
 if(!relatedClassDec) {
          return; //<--- should change to continue;
 }
```
After that change, it's working perfectly!

https://github.com/ngneat/aim/pull/31

**Comment by NetanelBasal** [comment]
Yes, that was a quick dummy fix. Thanks
